[2025-08-20T06:25:52.854+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finnhub_stock_pipeline.run_finnhub_producer manual__2025-08-20T06:25:50.137581+00:00 [queued]>
[2025-08-20T06:25:52.857+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finnhub_stock_pipeline.run_finnhub_producer manual__2025-08-20T06:25:50.137581+00:00 [queued]>
[2025-08-20T06:25:52.857+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-08-20T06:25:52.864+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_finnhub_producer> on 2025-08-20 06:25:50.137581+00:00
[2025-08-20T06:25:52.867+0000] {standard_task_runner.py:60} INFO - Started process 102 to run task
[2025-08-20T06:25:52.869+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'finnhub_stock_pipeline', 'run_finnhub_producer', 'manual__2025-08-20T06:25:50.137581+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/finnhub_pipeline.py', '--cfg-path', '/tmp/tmpfvfypkm4']
[2025-08-20T06:25:52.871+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask run_finnhub_producer
[2025-08-20T06:25:52.911+0000] {task_command.py:423} INFO - Running <TaskInstance: finnhub_stock_pipeline.run_finnhub_producer manual__2025-08-20T06:25:50.137581+00:00 [running]> on host 483bc26b07bd
[2025-08-20T06:25:53.057+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='finnhub_stock_pipeline' AIRFLOW_CTX_TASK_ID='run_finnhub_producer' AIRFLOW_CTX_EXECUTION_DATE='2025-08-20T06:25:50.137581+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-20T06:25:50.137581+00:00'
[2025-08-20T06:25:53.058+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-20T06:25:53.059+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python -u /opt/airflow/scripts/finnhub_producer.py']
[2025-08-20T06:25:53.065+0000] {subprocess.py:86} INFO - Output:
[2025-08-20T06:25:53.080+0000] {subprocess.py:93} INFO - python: can't open file '/opt/airflow/scripts/finnhub_producer.py': [Errno 2] No such file or directory
[2025-08-20T06:25:53.082+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-08-20T06:25:53.087+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-08-20T06:25:53.089+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=finnhub_stock_pipeline, task_id=run_finnhub_producer, execution_date=20250820T062550, start_date=20250820T062552, end_date=20250820T062553
[2025-08-20T06:25:53.102+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task run_finnhub_producer (Bash command failed. The command returned a non-zero exit code 2.; 102)
[2025-08-20T06:25:53.122+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-20T06:25:53.130+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
